- name: ACI Setup
  hosts: localhost
  connection: local
  gather_facts: false
 
  vars_files:
   - variable.yaml
  
  tasks:

  - name: Create XML template to delete contract
    template: src=delete_contract.j2 dest=delete_contract.xml
  - name: Create XML template to detach contract
    template: src=detach_contract.j2 dest=detach_contract.xml#
  - name: Create XML template for delete_deviceSelectionPolicy
    template: src=delete_deviceSelectionPolicy.j2 dest=delete_deviceSelectionPolicy.xml
  - name: Create XML template for delete_service_graph_template
    template: src=delete_service_graph_template.j2 dest=delete_service_graph_template.xml
  - name: Create XML template for delete_unmanaged_ve_ldev
    template: src=delete_unmanaged_ve_ldev.j2 dest=delete_unmanaged_ve_ldev.xml
  
  
  - name: Execute DELETE (Contract, Apply Contract to EPG, Create LDEV, Service Graph Template, Device selection policy , Apply graph)
    aci_rest:
      action: "post"
      #uri: "/api/node/mo/uni/tn-{{tenant_name}}.xml"
      path: "/api/node/mo/uni/tn-{{tenant_name}}.xml"
      #path: "/api/node/mo/uni/tn-{{tenant_name}}.xml/brc-{{contract_name}}.xml"
      config_file: "{{ item }}"
      host: 10.192.73.30
      username: admin
      password: cisco123
      validate_certs: "false"
    with_items:
     - "delete_contract.xml"
     - "detach_contract.xml"
     - "delete_deviceSelectionPolicy.xml"
     - "delete_service_graph_template.xml"
     - "delete_unmanaged_ve_ldev.xml"